---
title: "RNA-seq Workshop"
author: "Elyas Mohammadi"
date: "2026-08-06"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=TRUE,
  message=FALSE,
  warning=FALSE,
  fig.width=8,
  fig.height=5
)
```



# 1. Load packages

```{r libraries}
.libPaths("/Users/elyas.mohammadi/Library/CloudStorage/OneDrive-KarolinskaInstitutet/Projects/Project.manual.layers/Rsaves/R.Spatial")

## installation
# install.packages("ggplot2")
# install.packages("harmony")
# install.packages('Seurat')

library(ggplot2)
library(Seurat)
library(harmony)
```

# 2. Read count matrices

```{r}
CTL1_counts <- Read10X("./CTL1/")
LiDef1_counts <- Read10X("./LiDef1/")

dim(CTL1_counts)
dim(LiDef1_counts)

CTL1_counts[1:5,1:5]
LiDef1_counts[1:5,1:5]
```

# 3. Create Seurat objects

```{r}
CTL1 <- CreateSeuratObject(CTL1_counts, assay="RNA", project="CTL1",
                           min.cells=3, min.features=200)

LiDef1 <- CreateSeuratObject(LiDef1_counts, assay="RNA", project="LiDef1",
                             min.cells=3, min.features=200)
```

# 4. Add metadata

```{r}
CTL1$SampleID <- "CTL1"
CTL1$Condition <- "Control"

LiDef1$SampleID <- "LiDef1"
LiDef1$Condition <- "LiDef"
```

# 5. Quality control

```{r}
CTL1[["percent.mt"]] <- PercentageFeatureSet(CTL1, pattern="^mt-")
LiDef1[["percent.mt"]] <- PercentageFeatureSet(LiDef1, pattern="^mt-")

VlnPlot(CTL1, features=c("nFeature_RNA","nCount_RNA","percent.mt"), ncol=3)
VlnPlot(LiDef1, features=c("nFeature_RNA","nCount_RNA","percent.mt"), ncol=3)
```

# 6. Filter cells

```{r}
CTL1 <- subset(CTL1, subset=nFeature_RNA>300 & nFeature_RNA<6000 & percent.mt<5)
LiDef1 <- subset(LiDef1, subset=nFeature_RNA>300 & nFeature_RNA<6000 & percent.mt<5)
```

# 7. Merge samples

```{r}
combined <- merge(CTL1, y=LiDef1,
                  add.cell.ids=c("CTL1","LiDef1"),
                  project="Workshop")
```

# 8. Normalization

```{r}
combined <- NormalizeData(combined)
combined <- FindVariableFeatures(combined)
combined <- ScaleData(combined)
```

# 9. PCA

```{r}
combined <- RunPCA(combined)
ElbowPlot(combined)
DimPlot(combined, reduction="pca", group.by="SampleID")
```

# 10. Harmony integration

```{r}
combined <- RunHarmony(combined, group.by.vars="SampleID")
```

# 11. UMAP & clustering

```{r}
combined <- RunUMAP(combined, reduction="harmony", dims=1:20)
combined <- FindNeighbors(combined, reduction="harmony", dims=1:20)
combined <- FindClusters(combined, resolution=c(0.3,0.5))

DimPlot(combined, reduction="umap", label=TRUE)
```

# 12. Marker genes

```{r}
combined <- JoinLayers(combined)
markers <- FindAllMarkers(combined,
                          only.pos=TRUE,
                          min.pct=0.25,
                          logfc.threshold=0.25)

head(markers)

```

# 13. Save object

```{r}
saveRDS(combined, "Workshop_processed_seurat.rds")
```
